import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    position: "relative",
    width: "100%",
    height: "100%",
    paddingHorizontal: 16,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 32,
    backgroundColor: "#FFFFFF",
  },
  imgWrapper: {
    width: 343,
    height: 240,
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 32,
  },
  img: {
    width: "100%",
    height: 240,
    objectFit: "cover",
  },
  commentContainer: {
    position: "absolute",
    bottom: 16,
    left: 16,
    width: "100%",
    minHeight: 50,
    display: "flex",
    justifyContent: "center",
    paddingVertical: 16,
    paddingLeft: 16,
    paddingRight: 46,
    backgroundColor: "#F6F6F6",
    borderRadius: 40,
    fontSize: 16,
    fontWeight: 500,
    zIndex: 2,
  },
  contentContainer: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  iconWrapper: {
    position: "absolute",
    top: "50%",
    right: 8,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 34,
    height: 34,
    backgroundColor: "#FF6C00",
    borderRadius: 20,
  },
  containerList: {
    maxWidth: "100%",
    paddingHorizontal: 16,
    display: "flex",
    marginBottom: 72,
  },
  commentCard: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 32,
  },
  imgWrapperUser: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    overflow: "hidden",
  },
  imgUser: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  commentWrapper: {
    width: 299,
    padding: 16,
    borderRadius: 6,
    borderTopLeftRadius: 0,
    backgroundColor: "#F6F6F6",
  },
  commentWrapperRight: {
    width: 299,
    padding: 16,
    borderRadius: 6,
    borderTopRightRadius: 0,
    backgroundColor: "#F6F6F6",
  },
  commentText: {
    fontSize: 13,
    marginBottom: 8,
  },
  commentDate: {
    fontSize: 10,
    color: "#BDBDBD",
    textAlign: "right",
  },
  commentDateLeft: {
    fontSize: 10,
    color: "#BDBDBD",
    textAlign: "left",
  },
});
