import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 32,
    paddingBottom: 12,
    backgroundColor: "#FFFFFF",
  },
  iconWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 70,
    height: 40,
    backgroundColor: "#F6F6F6",
    borderRadius: 20,
  },
  formContainer: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 32,
  },
  imageContainer: {
    width: "100%",
    display: "flex",
    gap: 8,
  },
  imageWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: 240,
    backgroundColor: "#F6F6F6",
    borderRadius: 8,
  },
  iconWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 60,
    height: 60,
    borderRadius: "50%",
    backgroundColor: "#FFFFFF",
  },
  inputText: {
    fontSize: 16,
    color: "#BDBDBD",
  },
  inputsContainer: {
    width: "100%",
    display: "flex",
    gap: 16,
  },
  commonInput: {
    paddingVertical: 16,
    borderStyle: "solid",
    borderBottomWidth: 1,
    borderBottomColor: "#E8E8E8",
    color: "#212121",
    fontSize: 16,
  },
  locationWrapper: {
    position: "relative",
    marginBottom: 32,
    justifyContent: "center",
  },
  locationInput: {
    borderRadius: 8,
    paddingVertical: 10,
    paddingLeft: 24,
    borderStyle: "solid",
    borderBottomWidth: 1,
    fontSize: 16,
    color: "#212121",
  },
  locationIcon: {
    position: "absolute",
    top: "50%",
    transform: [{ translateY: -12 }],
    zIndex: 1,
  },
  submitButton: {
    width: "100%",
    paddingVertical: 16,
    borderRadius: 100,
    marginBottom: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FF6C00",
  },
  submitButtonText: {
    textAlign: "center",
    color: "#FFFFFF",
    fontSize: 16,
  },
});
